### PR TITLE
Feature/return visual of the solution

### LINKED ISSUE #3: Return a visual of the solution
Return an image of the max cut solution

### PR DESCRIPTION
**Pull request by m3ller**
Closes #3 

Plot and save the image of the max-cut solution.

### CODE REVIEW

**Comment by m3ller** [comment]
Here is a sample of the plot
image

**Comment by vgoliber** [comment]
Need to add matplotlib to requirements.txt

**Comment by m3ller** [comment]
I forgot to add the plotting code to the ising-version of this demo. I shall do that soon!

**Comment by vgoliber** [comment]
In readme file under usage mention the png file output (see antennas demo for example)

**Pull request merged**
